### PR TITLE
Code Review [1pt] Create basic structure for Missions - Setup #20 , [4pt] Display missions - Lists render #15 & [4pt] Fetch missions - Fetch data #18

### PR DESCRIPTION
**Pull request by amiraabouhadid**
## Description

This is a web app where users can book rockets and missions 

### General requirements
- [x] There are no linter errors.
- [x] Followed the **Github flow**.
- [x] The documentation is professional.
### HTML/CSS/JS requirements

- [x] We followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- [x] We followed the list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
### Project requirements

- Create a route and a view component. Use <NavLink /> for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.
- Use useSelector() Redux Hook to select the state slices and render lists of missions in corresponding routes.
- Fetch data from the Missions endpoint (https://api.spacexdata.com/v3/missions) when a user navigates to the Missions section. Once the data are fetched, dispatch an action to store the selected data in Redux store:
    - mission_id
    - mission_name
    - description
    - NOTE: Make sure you only dispatch those actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Comment by jssol** [comment]
@amiraabouhadid, I merged the other branch.
You will have to update this one before merging.

**Review by jssol — CHANGES_REQUESTED** [review]
Nice implementation of the store.
However, I'm getting these errors.
Axios is not being retrieved, try fixing it.

```
ERROR in ./src/redux/missions/missions.js 3:0-26
Module not found: Error: Can't resolve 'axios' in '/home/solotov/Documents/capstone-projects/space_travelers_hub/src/redux/missions'
resolve 'axios' in '/home/solotov/Documents/capstone-projects/space_travelers_hub/src/redux/missions'
  Parsed request is a module
  using description file: /home/solotov/Documents/capstone-projects/space_travelers_hub/package.json (relative path: ./src/redux/missions)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/solotov/Documents/capstone-projects/space_travelers_hub/src/redux/missions/node_modules doesn't exist or is not a directory
      /home/solotov/Documents/capstone-projects/space_travelers_hub/src/redux/node_modules doesn't exist or is not a directory
      /home/solotov/Documents/capstone-projects/space_travelers_hub/src/node_modules doesn't exist or is not a directory
      looking for modules in /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules
        single file module
          using description file: /home/solotov/Documents/capstone-projects/space_travelers_hub/package.json (relative path: ./node_modules/axios)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.jsx doesn't exist
        /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios doesn't exist
      /home/solotov/Documents/capstone-projects/node_modules doesn't exist or is not a directory
      /home/solotov/Documents/node_modules doesn't exist or is not a directory
      looking for modules in /home/solotov/node_modules
        single file module
          using description file: /home/solotov/package.json (relative path: ./node_modules/axios)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/node_modules/axios.jsx doesn't exist
        /home/solotov/node_modules/axios doesn't exist
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules
        single file module
          using description file: /home/solotov/Documents/capstone-projects/space_travelers_hub/package.json (relative path: ./node_modules/axios)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios doesn't exist
            .web.mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.web.mjs doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.mjs doesn't exist
            .web.js
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.web.js doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.json doesn't exist
            .web.jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.web.jsx doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios.jsx doesn't exist
        /home/solotov/Documents/capstone-projects/space_travelers_hub/node_modules/axios doesn't exist
 @ ./src/App.js 9:0-56 21:13-24
 @ ./src/index.js 8:0-24 14:33-36
```

**Comment by jssol** [comment]
> *

I have just reinstalled it and it works now `npm i -S axios`

**Comment by amiraabouhadid** [comment]
@jssol That's weird because it is installed in my branch

**Review by jssol — APPROVED** [review]
Nice job @amiraabouhadid,
The bootstrap UI looks great! :100:

**Pull request merged**
